vim.cmd("let mapleader=\",\"")
require("config.lazy")
require("conf.myconf")
require("conf.pconf")
require("conf.cmake-tools-conf")
require("conf.lualine-conf")
vim.cmd("colorscheme onelight")
vim.cmd("colorscheme onelight")
vim.cmd("CMakeSelectCwd /home/coding/学习平台")
vim.cmd("CMakeSelectBuildDir /home/coding/cmakeout")
vim.cmd("!rm ~/桌面/out")
vim.cmd("!rm ~/桌面/compile_commands.json")
vim.cmd("lua Snacks.dashboard()")
vim.cmd("!rm ~/桌面/*.json")

